### ISSUE TITLE
Index.html title and meta are in Portuguese VS rest of the site in English

### ISSUE THREAD

**Issue by diogorolo** [dialex/DiogoNunesCom#2]
In the index.html file, the page title and meta are in portuguese. Seeing that the rest of the site is in english, maybe it should also be translated?

https://github.com/dialex/DiogoNunesCom/blob/d8f24e965355504029e94428e2f9bd03f06df80a/index.html#L12-L13

**Comment by dialex** [comment]
I'm well aware of that. It's temporary and for SEO reasons. In time there will be a complete portuguese (alternative) page ;) Thanks!!
